/**
 * `docs/data/SEED.md` and `docs/data/IMAGES.md`, generated from the manifest and the
 * ledger. Every figure in them is counted from the files, never typed.
 */
import type { EntityDef, PackManifest } from '../../src/domain/model'
import type { PackImageEntry, PackImagesFile } from '../../src/data/pack/images'
import { countLedger, countVerdicts } from '../../src/data/pack/images'
import { plainly } from './ledger'

const n = (x: number): string => x.toLocaleString('en-AU')
const cell = (s: string): string => s.replace(/\|/g, '\\|')

export function seedDoc(manifest: PackManifest, entities: readonly EntityDef[]): string {
  const byId = new Map(entities.map((e) => [e.id, e]))
  const lines: string[] = []
  lines.push('# The seed pack')
  lines.push('')
  lines.push(
    `Generated by \`npm run pack\` from \`data/northside/manifest.json\`; do not edit. Packed ${manifest.packedAt} from the old repository's committed \`src/demos/northside.ts\` (sha256 \`${manifest.sourceSha256}\`, old fingerprint \`${manifest.sourceFingerprint}\`).`,
  )
  lines.push('')
  lines.push(
    `**${n(manifest.counts.tables)} tables · ${n(manifest.counts.rows)} rows · ${n(manifest.counts.joins)} joins.** Every value was read out of Northside Marine's Master Price File; every row carries a Source column naming the sheet and cell it came from. Modules and the two seeded flow rules are not data: the nine places are minted by app code from table keys.`,
  )
  lines.push('')
  lines.push(
    'Ids are deterministic: table = seed key, row = `key:ordinal`, field = `key.column`; the four `__` columns (`__origin`, `__recommended`, `__order`, `__discontinued`) keep their literal ids because the model reads them by string.',
  )
  lines.push('')
  lines.push('| key | name | kind | role | rows | declared levels | cost columns |')
  lines.push('|---|---|---|---|---:|---|---|')
  for (const t of manifest.tables) {
    const e = byId.get(t.id)
    const nameOf = (fieldId: string): string =>
      e?.fields.find((f) => f.id === fieldId)?.name ?? fieldId
    const levels =
      t.priceLevels && t.priceLevels.length > 0
        ? t.priceLevels.map((l) => `${l.key} → ${cell(l.label)} (${l.scope})`).join('<br>')
        : '— not priced'
    const cost =
      t.costColumns.length > 0 ? t.costColumns.map((c) => cell(nameOf(c))).join(', ') : '—'
    lines.push(
      `| \`${t.key}\` | ${cell(t.name)}${e?.retired ? ' *(retired)*' : ''} | ${t.kind ?? '—'} | ${t.role} | ${n(t.rowCount)} | ${levels} | ${cost} |`,
    )
  }
  lines.push('')
  lines.push('## Declared levels')
  lines.push('')
  lines.push(
    'The packer declares each priced table’s ladder from the old resolver’s exact-name list per kind (boat: Cash · Trade · Warranty; motor: Sell Price · Trade Price; trailer: Sell inc Rego; accessory: Sell · Sell inc Install (if appl.)) and refuses, by throwing, any rung that would land on a cost band. A table with no declared level is not priced: a quote leaves its amount for a person. Cost columns are named by the workbook’s own bands (“Cost Build”, “Cost Ladder”) and by the old cost list, and never reach a customer surface.',
  )
  lines.push('')
  return `${lines.join('\n')}\n`
}

export function imagesDoc(manifest: PackManifest, ledger: PackImagesFile): string {
  const images = ledger.images
  const counts = countLedger(images)
  const verdicts = countVerdicts(images)
  const byHost = new Map<
    string,
    { held: number; unheld: number; refused: number; mirror: number }
  >()
  for (const e of images) {
    const slot = byHost.get(e.host) ?? { held: 0, unheld: 0, refused: 0, mirror: 0 }
    if (e.file) slot.held += 1
    else if (e.error) slot.refused += 1
    else slot.unheld += 1
    if (e.via === 'mpf-mirror') slot.mirror += 1
    byHost.set(e.host, slot)
  }
  const lines: string[] = []
  lines.push('# The pictures')
  lines.push('')
  lines.push(
    `Generated from \`data/northside/images.json\` by the packer and by \`tools/seed/fetch-images.ts\`; do not edit. Last measured ${ledger.meta.measured}; held copies are WebP at long edge ${ledger.meta.longEdge}, quality ${ledger.meta.quality}.`,
  )
  lines.push('')
  lines.push(
    `**${n(images.length)} addresses: ${n(counts.held)} held · ${n(counts.unheld)} unheld · ${n(counts.refused)} refused.** A picture belongs only to the exact model it depicts: nothing is matched by resemblance and nothing is substituted. An unheld or refused address behaves the same way — the row keeps showing the address.`,
  )
  lines.push('')
  if (manifest.images.held !== counts.held || manifest.images.refused !== counts.refused) {
    lines.push(
      `> The manifest counts ${manifest.images.held} held and ${manifest.images.refused} refused, which differs from the ledger — re-run the packer.`,
    )
    lines.push('')
  }
  lines.push('## By host')
  lines.push('')
  lines.push('| host | held | of which off the mirror | unheld | refused |')
  lines.push('|---|---:|---:|---:|---:|')
  for (const [host, c] of [...byHost.entries()].toSorted((a, b) => (a[0] < b[0] ? -1 : 1))) {
    lines.push(`| ${host} | ${n(c.held)} | ${n(c.mirror)} | ${n(c.unheld)} | ${n(c.refused)} |`)
  }
  lines.push('')
  lines.push('## Verdicts, measured off the pixels')
  lines.push('')
  lines.push(
    `Of the ${n(counts.held)} held pictures, **${n(verdicts.scene)} are scenes** (a photograph with sky or water round its edge; may fill a chapter) and **${n(verdicts.studio)} are studio shots** (a render on paper or a neutral ground; sits large on a quiet ground). The edge ring of a 32×32 drawing is read once by the packer; an unheld picture is \`unknown\` and is treated like a studio shot, which can only make a screen quieter.`,
  )
  lines.push('')
  const refused = images.filter((e) => e.error)
  if (refused.length > 0) {
    lines.push('## Refused, with the measured reason')
    lines.push('')
    for (const e of refused) lines.push(`- ${e.address} — ${e.error}`)
    lines.push('')
  }
  const mirrored = images.filter((e) => e.via === 'mpf-mirror').length
  lines.push('## The mirror')
  lines.push('')
  lines.push(
    `${n(mirrored)} held copies came off the dealership's own mirror of the same address rather than off the host, because the host answers a plain request with a Cloudflare challenge. The mirror object is named \`mpf-mirror/{folder}/{sha1(address)[:16]}.{ext}\` — a function of the address the workbook typed — so a copy is asked for by name, never searched for, and a WordPress address that states its own pixel size (\`…-1024x683.jpg\`) must be served at exactly that size or it does not land. Each mirrored entry records the object and the key so the chain can be re-checked.`,
  )
  lines.push('')
  lines.push('## What is not here')
  lines.push('')
  lines.push(
    `Trailer rows on ${plainly('northsidemarine1.sharepoint.com')} point at brand logos behind a Microsoft sign-in; those rows stay honestly picture-less, and brand marks belong in \`public/brand-marks\` with their own provenance. Nothing in this ledger is a stand-in.`,
  )
  lines.push('')
  return `${lines.join('\n')}\n`
}

/** The refused entries alone, for a run report. */
export const refusedOf = (images: readonly PackImageEntry[]): PackImageEntry[] =>
  images.filter((e) => e.error !== undefined)
