/**
 * Serves `data/northside/` at `/data/northside/…`.
 *
 * The pack's source of truth is the `data/` folder at the repository root, generated by
 * `npm run pack` and read by `src/data/pack/load.ts`. Copying it into `public/` would make
 * a second copy that can go stale, so instead: in dev a middleware streams the files from
 * where they are, and at build the same files are emitted into `dist/data/northside/`,
 * which `vite preview` then serves like anything else in `dist`.
 */
import { createReadStream, existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Plugin } from 'vite'

const PREFIX = '/data/northside/'

function* walk(dir: string, rel = ''): Generator<string> {
  for (const name of readdirSync(dir)) {
    const abs = path.join(dir, name)
    const sub = rel === '' ? name : `${rel}/${name}`
    if (statSync(abs).isDirectory()) yield* walk(abs, sub)
    else yield sub
  }
}

export function servePack(): Plugin {
  const dir = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    '..',
    '..',
    'data',
    'northside',
  )
  return {
    name: 'hl2-serve-pack',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url ?? ''
        if (!url.startsWith(PREFIX)) {
          next()
          return
        }
        /* A REQUEST WITH A QUERY IS VITE'S, NOT THE APP'S. The app
           fetches a pack file by its plain address and never adds a
           query; Vite asks for the same file with one — `?raw`,
           `?import`, `?t=` — when a module imports it, and the answer
           then has to be a JS module rather than a JSON body. Serving
           JSON to a module request is a "MIME type application/json"
           failure in the browser, which is what home's two picture
           ledgers hit the first time one was imported rather than
           fetched. They ride in the bundle on purpose: nothing on home
           may fetch on a second visit, which is the promise
           `pack-loads.spec.ts` counts requests to check. */
        if (url.slice(PREFIX.length).includes('?')) {
          next()
          return
        }
        const rel = decodeURIComponent(url.slice(PREFIX.length).split('?')[0])
        const file = path.resolve(dir, rel)
        if (!file.startsWith(dir + path.sep) || !existsSync(file) || !statSync(file).isFile()) {
          res.statusCode = 404
          res.setHeader('Content-Type', 'text/plain; charset=utf-8')
          res.end(`The pack has no ${rel}.`)
          return
        }
        res.setHeader('Content-Type', 'application/json; charset=utf-8')
        res.setHeader('Cache-Control', 'no-cache')
        createReadStream(file).pipe(res)
      })
    },
    generateBundle() {
      if (!existsSync(dir)) return
      for (const rel of walk(dir)) {
        this.emitFile({
          type: 'asset',
          fileName: `data/northside/${rel}`,
          source: readFileSync(path.join(dir, rel)),
        })
      }
    },
  }
}
