/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as QuoteIdRouteImport } from './routes/quote.$id'
import { Route as QuoteNewRouteImport } from './routes/quote.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteNewRoute = QuoteNewRouteImport.update({
  id: '/quote/new',
  path: '/quote/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quotes': typeof QuotesRoute
  '/sign-in': typeof SignInRoute
  '/quote/$id': typeof QuoteIdRoute
  '/quote/new': typeof QuoteNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quotes': typeof QuotesRoute
  '/sign-in': typeof SignInRoute
  '/quote/$id': typeof QuoteIdRoute
  '/quote/new': typeof QuoteNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quotes': typeof QuotesRoute
  '/sign-in': typeof SignInRoute
  '/quote/$id': typeof QuoteIdRoute
  '/quote/new': typeof QuoteNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quotes' | '/sign-in' | '/quote/$id' | '/quote/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quotes' | '/sign-in' | '/quote/$id' | '/quote/new'
  id: '__root__' | '/' | '/quotes' | '/sign-in' | '/quote/$id' | '/quote/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuotesRoute: typeof QuotesRoute
  SignInRoute: typeof SignInRoute
  QuoteIdRoute: typeof QuoteIdRoute
  QuoteNewRoute: typeof QuoteNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/new': {
      id: '/quote/new'
      path: '/quote/new'
      fullPath: '/quote/new'
      preLoaderRoute: typeof QuoteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuotesRoute: QuotesRoute,
  SignInRoute: SignInRoute,
  QuoteIdRoute: QuoteIdRoute,
  QuoteNewRoute: QuoteNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
