/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DataIndexRouteImport } from './routes/data.index'
import { Route as DataTableRouteImport } from './routes/data.$table'
import { Route as QuoteIdRouteImport } from './routes/quote.$id'
import { Route as QuoteNewRouteImport } from './routes/quote.new'
import { Route as QuoteIdCascadeRouteImport } from './routes/quote.$id_.cascade'
import { Route as QuoteIdDocumentRouteImport } from './routes/quote.$id_.document'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTableRoute = DataTableRouteImport.update({
  id: '/data/$table',
  path: '/data/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteNewRoute = QuoteNewRouteImport.update({
  id: '/quote/new',
  path: '/quote/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdCascadeRoute = QuoteIdCascadeRouteImport.update({
  id: '/quote/$id_/cascade',
  path: '/quote/$id/cascade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdDocumentRoute = QuoteIdDocumentRouteImport.update({
  id: '/quote/$id_/document',
  path: '/quote/$id/document',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/history': typeof HistoryRoute
  '/quotes': typeof QuotesRoute
  '/sign-in': typeof SignInRoute
  '/data/$table': typeof DataTableRoute
  '/quote/$id': typeof QuoteIdRoute
  '/quote/new': typeof QuoteNewRoute
  '/data/': typeof DataIndexRoute
  '/quote/$id/cascade': typeof QuoteIdCascadeRoute
  '/quote/$id/document': typeof QuoteIdDocumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/history': typeof HistoryRoute
  '/quotes': typeof QuotesRoute
  '/sign-in': typeof SignInRoute
  '/data/$table': typeof DataTableRoute
  '/quote/$id': typeof QuoteIdRoute
  '/quote/new': typeof QuoteNewRoute
  '/data': typeof DataIndexRoute
  '/quote/$id/cascade': typeof QuoteIdCascadeRoute
  '/quote/$id/document': typeof QuoteIdDocumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/history': typeof HistoryRoute
  '/quotes': typeof QuotesRoute
  '/sign-in': typeof SignInRoute
  '/data/$table': typeof DataTableRoute
  '/quote/$id': typeof QuoteIdRoute
  '/quote/new': typeof QuoteNewRoute
  '/data/': typeof DataIndexRoute
  '/quote/$id_/cascade': typeof QuoteIdCascadeRoute
  '/quote/$id_/document': typeof QuoteIdDocumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/history'
    | '/quotes'
    | '/sign-in'
    | '/data/$table'
    | '/quote/$id'
    | '/quote/new'
    | '/data/'
    | '/quote/$id/cascade'
    | '/quote/$id/document'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/history'
    | '/quotes'
    | '/sign-in'
    | '/data/$table'
    | '/quote/$id'
    | '/quote/new'
    | '/data'
    | '/quote/$id/cascade'
    | '/quote/$id/document'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/history'
    | '/quotes'
    | '/sign-in'
    | '/data/$table'
    | '/quote/$id'
    | '/quote/new'
    | '/data/'
    | '/quote/$id_/cascade'
    | '/quote/$id_/document'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  HistoryRoute: typeof HistoryRoute
  QuotesRoute: typeof QuotesRoute
  SignInRoute: typeof SignInRoute
  DataTableRoute: typeof DataTableRoute
  QuoteIdRoute: typeof QuoteIdRoute
  QuoteNewRoute: typeof QuoteNewRoute
  DataIndexRoute: typeof DataIndexRoute
  QuoteIdCascadeRoute: typeof QuoteIdCascadeRoute
  QuoteIdDocumentRoute: typeof QuoteIdDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$table': {
      id: '/data/$table'
      path: '/data/$table'
      fullPath: '/data/$table'
      preLoaderRoute: typeof DataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/new': {
      id: '/quote/new'
      path: '/quote/new'
      fullPath: '/quote/new'
      preLoaderRoute: typeof QuoteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id_/cascade': {
      id: '/quote/$id_/cascade'
      path: '/quote/$id/cascade'
      fullPath: '/quote/$id/cascade'
      preLoaderRoute: typeof QuoteIdCascadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id_/document': {
      id: '/quote/$id_/document'
      path: '/quote/$id/document'
      fullPath: '/quote/$id/document'
      preLoaderRoute: typeof QuoteIdDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  HistoryRoute: HistoryRoute,
  QuotesRoute: QuotesRoute,
  SignInRoute: SignInRoute,
  DataTableRoute: DataTableRoute,
  QuoteIdRoute: QuoteIdRoute,
  QuoteNewRoute: QuoteNewRoute,
  DataIndexRoute: DataIndexRoute,
  QuoteIdCascadeRoute: QuoteIdCascadeRoute,
  QuoteIdDocumentRoute: QuoteIdDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
